### ISSUE TITLE
Mac version does not work (not notarized)

### ISSUE THREAD

**Issue by jstaerk** [ZUGFeRD/quba-viewer#101]
As Mr. Dietrich remarked the Mac version would not start (Quba kann nicht geöffnet werden da der Entwickler nicht authentifiziert werden kann). My fault (Jochen), apparently I pressed the wrong button to release, @akemlek confirmed it's not notarized. 
Apparently my `npm run publish` does not notarize whereas `npm run build`(?) does(?). 

As mentioned I caused the mistake, nevertheless assigning to Mert for the next step because he now needs to rebuild :-/

**Comment by jstaerk** [comment]
We're almost there, @akemlek fixed the build for the master version so all we have to do is rebuild and republish the 1.4.2

**Comment by jstaerk** [comment]
Please try again, same link, https://quba-viewer.org/files/Quba-1.4.2-universal.dmg

**Comment by neuffer** [comment]
I can confirm that the new version indeed installs fine now on MacOS.

I however stumbled over a bug with embedded PDFs (Rechnungsbegründende Dateien) in Zugferd Invoices.
The same file embedded to an XRechnung displays fine in Quba.
Both invoices created with the PDF24.org E-Rechnung tool.
I'll open another issue for this and add 2 sample files

**Comment by jstaerk** [comment]
the attachment issue may be a duplicate of #29 but thanks for reporting anyway and thanks for confirming the mac fix
