### ISSUE TITLE
Command line arguments

### ISSUE THREAD

**Issue by michael-barchy-cpasbxl** [ZUGFeRD/quba-viewer#12]
Could you add the possibility to open a file from command line (or File > Open...) ?
`Quba myfile.xml`
Thanks. Regards. Michael

**Comment by asimkhanaup** [comment]
Thanks for using Quba. We have already added that functionality. We will release the new version of Quba in the upcoming days. Thanks

**Comment by michael-barchy-cpasbxl** [comment]
Great! Thanks 👍
