### ISSUE TITLE
No close button for attachments

### ISSUE THREAD

**Issue by jstaerk** [ZUGFeRD/quba-viewer#15]
If a XRechnung has embedded files, like [this one](https://github.com/ZUGFeRD/quba-viewer/files/8752922/xrechnung.txt) quba will show a open-link and the attachment but then the close icon is missing in the popup->there is no possibility to close the attachment view

![image](https://user-images.githubusercontent.com/3964386/169780130-62edb553-6b22-491c-8f43-50af4be74711.png)

**Comment by asimkhanaup** [comment]
OK got it I will fix it.

**Comment by asimkhanaup** [comment]
Done. Code pushed.

**Comment by jstaerk** [comment]
main window is now displayed black 
![image](https://user-images.githubusercontent.com/3964386/170932567-ed72188e-f2db-4d37-b90b-f76889ae7056.png)

**Comment by jstaerk** [comment]
has been closed in 1.1.4
