### ISSUE TITLE
XML invoice with large PDF (approx. > 1.4 MB) attached can't be opened

### ISSUE THREAD

**Issue by xiangmai** [ZUGFeRD/quba-viewer#16]
Large PDF attachments cause an error so that invoices can't be opened in the viewer.

**Comment by xiangmai** [comment]
(The Quba viewer remains black.)

**Comment by asimkhan21** [comment]
Could you please attach here a sample PDF file so that I can reproduce it?. For me, a large PDF file >20MB works fine.

**Comment by xiangmai** [comment]
Hi, thanks for your reply. It took a while to get an example PDF from my colleague. Now I have it, but I cannot upload it here ("We don't support that file type." - It's just an XML file.). Can I send it to you some other way?

**Comment by xiangmai** [comment]
Hi,
I have now managed to upload an example file that doesn't work for us. I had to zip it.
[ubl21.zip](https://github.com/ZUGFeRD/quba-viewer/files/9290869/ubl21.zip)

**Comment by asimkhanaup** [comment]
Hi, thanks we have already fixed this issue. I checked your attachment and it is working on the new version of Quba.  Next week hopefully we will release the new version of Quba. Thanks
