### ISSUE TITLE
Cannot start quba on macOS Monterey 12.5

### ISSUE THREAD

**Issue by meabacus** [ZUGFeRD/quba-viewer#19]
Cannot start quba on macOS Monterey 12.5. Error Message: This program is not supported on this Mac.
<img width="289" alt="Bildschirmfoto 2022-09-22 um 16 30 53" src="https://user-images.githubusercontent.com/114167484/191775229-63ca278a-6b4a-49d4-a468-e0289700e530.png">

**Comment by jstaerk** [comment]
hi,
Unfortunately we only test on 12.1, but there's a prototype version available based on electron 20 (instead of 14), 
that should work, would you volunteer to give it a try?

kind regards
Jochen

**Comment by jstaerk** [comment]
The new version is released, this could work now. If it doesn't: we still look for users with intel macs.
