### ISSUE TITLE
X-Rechnung 2.1/2.2 CreditNote (UBL) not working

### ISSUE THREAD

**Issue by vbkredeemer** [ZUGFeRD/quba-viewer#24]
"File format not recognized" for UBL-CreditNote.

I was not able to open:
- XSD Schema UBL-CreditNote-2.1.xsd
- Schematron (XSLT) CEN-EN16931-UBL
- Schematron (XSLT) XRechnung 2.2.0

**Comment by jstaerk** [comment]
no, you are right, that's something different. I had been looking for typecode 389=self billed invoice. Does anybody know why this distinction is apparently required in UBL (and not in CII?)? And is there a sample to be found anywhere?

**Comment by jstaerk** [comment]
can you please try if http://www.quba-viewer.org/quba_viewer-1.2.2.exe works for you?

**Comment by vbkredeemer** [comment]
Now it works. Just perfect. You are the best. :-) 
Now we finaly have a useable alternative for us. 
Thank you very much for your work!!!
