### ISSUE TITLE
Use Quba as standardapplication for XML

### ISSUE THREAD

**Issue by vbkredeemer** [ZUGFeRD/quba-viewer#25]
I have set up Quba as a stadard application for XML to make it easier to work with X-invoices. If you open the first file with Quba everything works fine. If you then open the second file and Quba is still open with the first, then the second file does not open. It seems that Windows tries to open Quba a second time, but closes it immediately. This is also the case when Quba is open without an open file. Once Quba is already started, no other file can be opened directly. 
Is it possible to define Quba so that it can be started multiple times, or within Quba also a second tab is opened when a file is opened directly from Windows.

**Comment by jstaerk** [comment]
the colleague can reproduce the issue

**Comment by jstaerk** [comment]
we fixed it and will soon release a new version

**Comment by vbkredeemer** [comment]
Perfekt. Thx. Can't wait to see the new Version.
