### ISSUE TITLE
Cannot open on M1/ M2 

### ISSUE THREAD

**Issue by pgtaboada** [ZUGFeRD/quba-viewer#26]
Hi there,

we tried to open the dmg file we downloaded from the homepage on 3 different macOs ventura notebooks. In german it says the file is "damaged".

Are we the only ones?

**Comment by mrwatson-de** [comment]
Same here - until this is fixed Quba is dead on arrival for modern Mac users.

Bump!

**Comment by jstaerk** [comment]
... finally! it works in the downloadable 1.4.0 from the homepage.
