### ISSUE TITLE
Items Net list price is the Gross Price

### ISSUE THREAD

**Issue by kuhnleag** [ZUGFeRD/quba-viewer#39]
it is possible that the net list price field is incorrectly assigned?
I mean, it's the value of the GrossPriceProductTradePrice from the xml ...
![quba](https://github.com/ZUGFeRD/quba-viewer/assets/156433547/0108e843-4a89-41ae-be39-a248a54aff97)

**Comment by jstaerk** [comment]
the "gross price" _is_ in fact a net list price, explicitly exclusively VAT, in both CII and UBL
