### ISSUE TITLE
„Quba“ ist beschädigt und kann nicht geöffnet werden.

### ISSUE THREAD

**Issue by rosch100** [ZUGFeRD/quba-viewer#47]
Quba Release 1.4.0 startet nicht auf M1 MacBook Pro mit MacOS 14.5.
Die Fehlermeldung lautet: 
"„Quba“ ist beschädigt und kann nicht geöffnet werden."

Die Version zu #23 (https://quba-viewer.org/files/issue23_quba_intel.dmg) funktioniert jedoch.

**Comment by jstaerk** [comment]
Hallo,
kann ich bitte mal kurz einen Screenshot von 
Apple  > Über diesen Mac
bekommen?

danke
Jochen

**Comment by rosch100** [comment]
<img width="193" alt="Bildschirmfoto 2024-05-27 um 15 25 31" src="https://github.com/ZUGFeRD/quba-viewer/assets/5745224/a4c56bbb-f34b-4eda-9bd6-bc0e7b899995">

**Comment by akemlek** [comment]
Hallo @rosch100, kannst du erneut eine frische Version von https://quba-viewer.org/ downloaden? Ich habe die gleiche Version wie du und habe keinerlei Probleme.

**Comment by rosch100** [comment]
Vielen Dank! Jetzt funktioniert es.

**Comment by Skulli** [comment]
Die Version unter https://github.com/ZUGFeRD/quba-viewer/releases/tag/v1.4.0 funktioniert nicht, die von der Homepage hingegen schon.
