### ISSUE TITLE
MSI Setup For Automated/Quiet/Silent Installation

### ISSUE THREAD

**Issue by PC-SPEZIALIST** [ZUGFeRD/quba-viewer#53]
Thanks for this awesome tool.
Would it be possible to create the setup as .msi package?
The [N‑able N‑sight RMM](https://www.n-able.com/products/n-sight-rmm) we use for workstation management supports silent installs in the background using parameters like [/qn](https://learn.microsoft.com/en-us/windows/win32/msi/standard-installer-command-line-options) for example.

![Quba-Viewer](https://github.com/user-attachments/assets/e7f0c07f-0198-493e-b164-1aff03ed2734)

**Comment by jstaerk** [comment]
difficult, maybe if commercially sponsored but maybe the silent install options somebody found on https://groups.google.com/g/zugferd/c/GBvkE_hqt4o can help?

**Comment by PC-SPEZIALIST** [comment]
> difficult, maybe if commercially sponsored but maybe the silent install options somebody found on https://groups.google.com/g/zugferd/c/GBvkE_hqt4o can help?

Thank you very much, @jstaerk! That works. 👍 

![quba](https://github.com/user-attachments/assets/6f006804-d91d-4b77-83f3-6ddc3251af9a)

**Comment by HIhnen** [comment]
We used Advanced Installer Freeware to build a msi file for Alluser deployment.

**Comment by jstaerk** [comment]
MSI version is now included

**Comment by PC-SPEZIALIST** [comment]
> MSI version is now included

Wow, you're awesome! Thank you so much!
