### ISSUE TITLE
New document shows still old data / invoice

### ISSUE THREAD

**Issue by borishinzer** [ZUGFeRD/quba-viewer#6]
I am using the Mac version 1.0.0. 
If I am opening an new xRechnung document in quba viewer, the app still shows the old data / invoice.
The only way to prevent this from happing is closing the app and restarting it for every new document.

**Comment by jstaerk** [comment]
Thanks, that's reproducible in windows as well, steps to reproduce: open xml file in Quba, change something in the file (e.g. GrandTotalAmount,  DuePayableAmount), open the file again, the old values are shown. Even if it's not clear if the tab is replaced but the problem also occurs when one closes the tab and opens the file again (as long as the filename does not differ from the previous version).

**Comment by jstaerk** [comment]
Will be fixed in version 1.1 which we'll try to publish in the course of this month
