### ISSUE TITLE
Erratic behaviour on win10

### ISSUE THREAD

**Issue by jstaerk** [ZUGFeRD/quba-viewer#73]
I'd **not** add win10 as supported platform in #58 because there seem to be numerous issues, maybe someone wants to have a look into it?
e.g. after installation and clicking on the icon on the desktop I am told the .lnk (!?? WTF???)  would not be assigned a application, the only way for me to start it is extracting the installer exe , the the app.64bit.7zip, each with 7-zip. Afterwards, it seems to work quite flawlessly on my machine but there is also the report that it sometimes just freezes or just shows [object Object] (with the official mustang sample invoice!)

like here
![image](https://github.com/user-attachments/assets/ff0a30f8-899f-4c9e-a5f1-2ea19930eaed)

**Comment by winnyschuster** [comment]
mhmm, i think the only 'issue' i had with the viewer was that it wanted a higher version of the jre, forcing me to install the newest openjdk. After that i didn't see any of the errors described above. However, if you'd like me to do whatever tests just let me know, i'm pretty new to the topic but not unexperienced in genaral:-)

**Comment by jstaerk** [comment]
@winnyschuster a electron, i.e. javascript application should not require you to install a JRE at all?

**Comment by winnyschuster** [comment]
upps, sorry, you are indeed right, it seems i was doing too many things at once to get an overview of all that e-invoicing stuff
