### ISSUE TITLE
DRag&Drop does not work

### ISSUE THREAD

**Issue by hastasoft** [ZUGFeRD/quba-viewer#82]
Tying to validate a xml-file (the same file works with 1.4.0), I habe the message "A Java script error occured in the main process
![Bild-04859BF2-F2C](https://github.com/user-attachments/assets/6bd957e5-7027-4b67-979c-695df4d323af)

**Comment by jstaerk** [comment]
was a regression from electron 33, sth had been deprecated in favor of webutils,  https://stackoverflow.com/questions/68104292/how-to-drop-a-file-from-explorer-and-get-its-full-path-to-electronjs-app
